source              : .
destination         : ./_site

# Handling Reading
include             : ["**/*.md","**/*.markdown"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Plugins

# Conversion
markdown            : kramdown

# Markdown Processors
kramdown:
  show_warnings     : true
sass:
  sass_dir: _sass
site:
  github:
    repository_url: "https://github.com/tpkowastaken/test-jekyll.github.io"
