source              : .
destination         : ./_site

# Handling Reading
include             : ["*.md","*.markdown"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Plugins
plugins:
  - jekyll-toc

# Conversion
markdown: kramdown

# Markdown Processors
kramdown:
  show_warnings: true
  input: GFM
  auto_ids: true
  toc_levels: 1..6
sass:
  sass_dir: _sass

github_repository_url: "https://github.com/tpkowastaken/test-jekyll.github.io"
github_repository_nwo: "main"
site_url: "https://tpkowastaken.github.io/test-jekyll.github.io"
