source              : .
destination         : ./_site

# Handling Reading
include             : ["**/*.md","**/*.markdown"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Plugins

# Conversion
markdown            : kramdown

# Markdown Processors
kramdown:
  show_warnings     : true
