theme               : jekyll-theme-minimal
source              : .
destination         : ./_site

# Handling Reading
include             : ["*.md","*.markdown"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Plugins
plugins             : ["jekyll-feed"]

# Conversion
markdown            : kramdown

# Markdown Processors
kramdown:
  show_warnings     : true
