name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Permissions
      run: |
        sudo chown -R $USER .
        sudo chmod -R 777 .
        
    - name: Install Dependencies
      run: |
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        sudo gem install bundler
        sudo bundle install

    - name: Build with Jekyll
      uses: docker://jekyll/builder:latest
      with:
        entrypoint: jekyll
        args: build --config _config.yml --source ./ --destination ./_site --incremental
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
        
    - name: Commit changes
      run: |
        git config --global user.email "protitom@gmail.com"
        git config --global user.name "tpkowastaken"
        git add _site
        git commit -m "Build Jekyll site"
        git push https://${{ secrets.TOKEN }}@github.com/tpkowastaken/test-jekyll.github.io.git HEAD:main

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2







