name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Jekyll
      run: gem install jekyll bundler

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build --destination _site
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: site
        path: _site
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update site"
        commit_options: "--author='GitHub Actions <actions@github.com>'"
        branch: main
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"


