name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Jekyll
      run: gem install jekyll bundler

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build --destination _site
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: site
        path: _site
    - name: Push changes
      env:
        token: ${{ secrets.TOKEN }}
      run: |
        git config --global user.name 'tpkowastaken'
        git config --global user.email 'protitom@gmail.com'
        git add _site
        git commit -m "build jekyll bot"
        git push origin main





