name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Jekyll
      run: gem install jekyll bundler

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build --destination _site
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
    - name: Commit changes
      run: |
        git config --global user.email "protitom@gmail.com"
        git config --global user.name "tpkowastaken"
        git add -A
        git commit -m "Build Jekyll site"
        git push https://${{ secrets.TOKEN }}@github.com/tpkowastaken/test-jekyll.github.io.git HEAD:main





